import '../img/cart-icon.png';
import '../img/mercedes-benz.svg';
import '../img/audi.svg';
import '../img/bmw.svg';
import '../img/audi_active.svg';
import '../img/bmw_active.svg';
import '../img/mercedes-benz_active.svg';
import '../img/cabriolet/audi tt roadster cabriolet_.png';
import '../img/cabriolet/bmw-m850i_cabriolet.png';
import '../img/cabriolet/bmw_m8_cabriolet.png';
import '../img/cabriolet/faw-audi-a3_cabriolet.png';
import '../img/cabriolet/mercedes cabriolet_e220.png';
import '../img/cabriolet/audi_a5-cabrio-individual.png';
import '../img/cabriolet/bmw-m440i-xdrive-cabrio-.png';
import '../img/cabriolet/Mercedes_convertible-slc.png';
import '../img/cabriolet/mercedes cabriolet_560.png';
import '../img/jeep/audi_Q7_jeep.png';
import '../img/jeep/audi_m4m4-district-green_jeep.png';
import '../img/jeep/Audi_Q2_jeep.png';
import '../img/jeep/bmw-x5-m-jeep.png';
import '../img/jeep/bmw-x-series-x2-jeep.png';
import '../img/jeep/bmw-x3-m40i-jeept.1654073422036.png';
import '../img/jeep/mercedes-GLA-jeep.png';
import '../img/jeep/mercedes benz glc_.png';
import '../img/jeep/mercedes_glc_x253_Jeep.png';
import '../img/sports car/audi_r8_sport car.png';
import '../img/sports car/audi_R8_sportcar_green.png';
import '../img/sports car/AUDi_r8_sportcar.png';
import '../img/sports car/bmw-m4-spotrs car.png';
import '../img/sports car/2022-BMW-M4-sportcar.png';
import '../img/sports car/bmw-m8-sportcar.png';
import '../img/sports car/bmw_b8_sportcar.png';
import '../img/sports car/mercedes amg gt r sports car.png';
import '../img/sports car/Mercedes amg_Gt_sport_car.png';
import '../img/sports car/mercedes benz amg gt sportcar.png';
import '../img/sports car/bmw_m4_sportcar.png';
import '../img/delete-btn.svg';
